### ISSUE TITLE
Split master / gh-pages

### ISSUE THREAD

**Issue by mathiasbynens** [v8/api#3]
After some fiddling with branches as well as c545e04cbf9a7b3bb20c2a94b1e72b59b964ac63 and eb897c1eaba238f46f8a72c8a38dbe2aa80d443f, the GitHub Action now shows up in [the Actions UI](https://github.com/v8/api/actions?query=workflow%3A%22Update+API+documentation%22) and we can now manually trigger it from there.

Ideally, this repository would be split into two branches:

- `master`, which contains only the LICENSE, the README, and the build script + dependencies
- `gh-pages`, which contains only the build output

That way, we can change the workflow to run on every push to `master` in addition to once per day through `cron`:

```
on:
  push:
    branches:
      - master
  schedule:
    # Rebuild docs every day at 3am.
    - cron: "0 3 * * *"
```

We'd have to tweak the workflow to deploy the result to the `gh-pages` branch.

FWIW, https://github.com/puppeteer/ispuppeteerfirefoxready/blob/master/.github/workflows/main.yml is a simple example of a similar workflow. It builds from `master` into the `dist` directory, and then deploys the contents of `dist` to `gh-pages`.
